### ISSUE TITLE
Feature request: full width & height 'embeds'

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-layout#104]
## What
Add the ability to have an o-layout header and/or footer above/below something which fills the screen. The use case is for branding and preserving site wide nav when embedding a tool which, for UX or technical reasons, expects to fill the browser window. The particular use case I have is [embedding graphql-playground in biz-ops-admin] (https://biz-ops.in.ft.com/api-explorer).

## Details
The changes needed to make this work were quite minimal: 100% height and width on the iframe, and 2 css blocks https://github.com/Financial-Times/biz-ops-admin/pull/336/files#diff-c6ff5e3873f3d9de522da667e08e69b1.

Probably not the most elegant implementation, but certainly achievable by means of some modifier class.

**Comment by notlee** [comment]
- o-layout is full-bleed by default if you remove the `o-layout--docs` modifier (I'm not sure that's in the readme, will add!). 
- o-header-services supports full-width pages with `o-header-services--bleed`. 
- I think resizing the iframe is probably appropriate for the project to do.

Does that cover your issue, removing the need for any overrides?
