### ISSUE TITLE
Feature request: Sticky sidebars in the query layout

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-layout#124]
David Balfour is working on a Spark prototype which uses the query layout of o-layout.
They would like the sidebars to be sticky on scroll.
<img width="1099" alt="Screenshot 2020-02-05 at 14 16 19" src="https://user-images.githubusercontent.com/10405691/73849637-2bd9bf80-4822-11ea-847c-9fad8fcd53d0.png">

Our registry already has sticky sidebars within the query layout, thanks to custom CSS
<img width="1317" alt="Screenshot 2020-02-05 at 14 18 17" src="https://user-images.githubusercontent.com/10405691/73849759-5deb2180-4822-11ea-9116-c220a9368a13.png">

**Comment by chee** [comment]
<https://github.com/Financial-Times/o-layout/pull/132/commits/2bd9e75181c46ea0e290212ba04bc575f2f7988f>
