### ISSUE TITLE
Support Masterbrand Layouts

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/o-layout#134]
I've just been speaking to @edds (a vendor asked if they have guidance on page layout stuff for FT.com content), and also we may have to produce something like this if we end up building something for the [Microsites proposal](https://docs.google.com/document/d/1K_bst9wGoWg6LnAEccDF-XlEV2LXvXIKRQJjXKRFOLQ/edit).

I know this is likely to be difficult as this currently makes extensive use of CSS grid. Possibly it'd be different enough that it should be a new component.

Opening this issue as a placeholder for discussion.

**Comment by JakeChampion** [comment]
We're soon to be looking at making the wordpress theme (the solution for microsites) capable for master branded content and o-layout was mentioned as a component which would need work done to support master brand.

We should look into the browser support policy for these microsites, maybe they don't support IE and can use CSS grid? 🤞

**Comment by notlee** [comment]
>We should look into the browser support policy for these microsites, maybe they don't support IE and can use CSS grid? 🤞

With a considered fallback, I'm hopeful that will be ok!

**Comment by JakeChampion** [comment]
This has come back up again now that the microsites project has made progress.

Some products want to use the microsites system with a master branded product, which means we need to assign some time to look into making a master branded layout component.

I see the last time we had this conversation, we were wondering if we need to support IE. I've raised the question with Mark Ridley.

**Comment by chee** [comment]
https://github.com/Financial-Times/o-layout/blob/85bf80877f23c7b02065dd49ffa3d7ae1c7a43c4/origami.json#L13
https://github.com/Financial-Times/o-layout/commit/0cf04080015c244da83ec2583259c33ca21516bb
