### ISSUE TITLE
¶ vs. # vs. 🔗 vs. anything else

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/o-layout#24]
We seem to have had a discussion a while ago that we never recorded anywhere, that led us to settle on the pilcrow as an indicator that we can link to a particular heading, so we don't know what the original justification is. 

We'll leave this issue open in case anyone has any opinions about the linked heading being a pilcrow.

**Comment by JakeChampion** [comment]
I think we should use a link marker such as 🔗 because the Pilcrow has a different meaning which is to mark paragraphs, not headings.

**Comment by JakeChampion** [comment]
Yes, `#` is an excellent suggestion :-)

**Comment by JakeChampion** [comment]
Aside: GitHub use the link icon <img width="140" alt="screen shot 2018-08-31 at 13 31 17" src="https://user-images.githubusercontent.com/1569131/44912478-2ec5ac00-ad22-11e8-8b72-9388d76fc350.png">

**Comment by notlee** [comment]
The `o-icons` 🔗icon might infer other behaviour, i.e. copy to clipboard.

`#` is 👍 by me

**Comment by rowanmanning** [comment]
I don't have strong opinions in any direction. Happy to go ahead with #️⃣too
