### ISSUE TITLE
Overrides primary button text colour

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-layout#27]
![image](https://user-images.githubusercontent.com/447559/46163023-e3031580-c281-11e8-8751-401b44ba0e93.png)

**Comment by gvonkoss** [comment]
`o-layout` has a wrapper that styles the semantic elements that might be added to the body, which includes anchor tags. The alternative would be to add individual classes to every anchor in a body, and we want to allow as much of the elements in a body to inherit from `o-layout` as possible. In this case, we recommend you use an anchor tag. 

Closing this but let us know if you have an alternative idea or a suggestion to change the behaviour!
