### ISSUE TITLE
Temporary issue: aside

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/o-layout#36]
In Chrome 70+ the asides are not working as expected, due to some part of the UA release — a fix is targeted fro Chrome 72: https://bugs.chromium.org/p/chromium/issues/detail?id=910953&q=css%20grid&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by notlee** [comment]
This is no longer an issue in [v3](https://github.com/Financial-Times/o-layout/pull/43). To position the main content area / aside, we replaced CSS Grid with floats. 🎉 

_CSS Grid is sooooo 2018_
