### ISSUE TITLE
Firefox: document height on resize or table sort

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-layout#50]
Firefox has a bug which causes table margin to render incorrectly and the page to infinitely grow on table sort or window resize. 

**Work around:**
To work around, wrap `table` elements in a `div`.

**Reduced test case:**
The table is rendered after the final paragraph, for some reason:
https://codepen.io/notleemoody/pen/xmJbxG
<img width="779" alt="screenshot 2019-01-09 at 10 35 19" src="https://user-images.githubusercontent.com/10405691/50894218-9390c180-13fa-11e9-9ff9-966973742b8a.png">

**Related bug reports:**
https://bugzilla.mozilla.org/show_bug.cgi?id=1505410

**o-layout resizing:**
![kapture 2019-01-09 at 10 43 04](https://user-images.githubusercontent.com/10405691/50894547-65f84800-13fb-11e9-9346-a6ba2e491b40.gif)

**Comment by JakeChampion** [comment]
How come this is a wontfix if there is a fix for the bug?

**Comment by notlee** [comment]
o-table isn't a dependency on o-layout. The issue is here just to flag a common problem. Although I should update the demos.

**Comment by notlee** [comment]
This is no longer an issue in [v3](https://github.com/Financial-Times/o-layout/pull/43). For the main content area, we replaced CSS Grid with floats. 🎉 

_CSS Grid is sooooo 2018_
