### ISSUE TITLE
Sitebar doesn't work without anchors

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/o-layout#84]
https://github.com/Financial-Times/o-layout/blob/b16b1eacc56d7e3bcc05b4b2cd5254838135e124/src/js/layout.js#L128

I'm trying out o-layout as part of https://github.com/Financial-Times/next/issues/349.

Some good success at https://customer-products.in.ft.com/wiki/Home, but I'm having trouble with the sidebar.

The logic linked above assumes that links in the sidebar will always be anchors.

I'm aware I'm probably abusing it's use, so this may well turn into a how to use o-header-services issue.

**Comment by gvonkoss** [comment]
👋 The side bar was intended for in-page navigation—so you're right, `o-heaer-services` can probably be a solution for this. 

We've recently added the option of adding [drop-down menus to the primary nav](https://www.ft.com/__origami/service/build/v2/demos/o-header-services@3.2.10/drop-down-navigation?brand=internal) in `o-header-services`:
<img width="1272" alt="Screenshot 2019-04-11 at 09 37 55" src="https://user-images.githubusercontent.com/16777943/55942978-85428380-5c3d-11e9-88a8-1aeef53cffec.png">

How does that sound?

**Comment by sjparkinson** [comment]
I will give it a spin, feels like the right thing to do 👍.

**Comment by notlee** [comment]
Plus one to this 👍 . Another approach is to use a landing page and subnav (like origami.ft.com), which might suit larger sections of the site, like the Developer Guide.
<img width="1392" alt="Screenshot 2019-04-15 at 11 13 24" src="https://user-images.githubusercontent.com/10405691/56124943-b25da180-5f6f-11e9-977e-4d550dddd878.png">

**Comment by sjparkinson** [comment]
We've rejiged our sidebar to conform, and it works a treat.
