### ISSUE TITLE
Content header typography

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/o-layout#88]
## What

The weighting of h2 and h3 headers doesn't help to convey their levels, in my naïve opinion.

## Details

The bold h3 feels very dominant compared to the h2 elements, could we maybe not adjust the weighting for h3 elements?

![image](https://user-images.githubusercontent.com/51677/57621428-4dec2d00-7583-11e9-8ac4-1f4463406722.png)

At a weight of `400` and size of `26px` I think it looks okay.

![image](https://user-images.githubusercontent.com/51677/57621563-b0ddc400-7583-11e9-91d4-aa254bc282a1.png)

## Additional information

* https://customer-products.in.ft.com/wiki/2019-Tech-Strategy#the-next-two-areas-we-will-pick-up

**Comment by notlee** [comment]
Thanks for the detailed issue with a link! 

I think you make a good point. We fairly recently updated our heading styles with the uxd team but it's something we can refine together as part of our work towards a major update of o-typography later this year. I've [created an issue on o-typography](https://github.com/Financial-Times/o-typography/issues/191) which will pull through to o-layout, so I'll close this one.
