### ISSUE TITLE
Third tier navigation scroll button is partly hidden

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/o-layout#90]
## What

If there are many navigation items, and the content is long enough, on desktop the scroll button is partly hidden.

![image](https://user-images.githubusercontent.com/51677/58038848-03d9ed00-7b29-11e9-84cf-20ba7267332b.png) ![image](https://user-images.githubusercontent.com/51677/58038724-ae054500-7b28-11e9-8b69-64007c95df74.png)

## Details

See https://customer-products.in.ft.com/wiki/Developer-Overview for an example.

**Comment by chee** [comment]
this appears to have been fixed at some point. i've checked on firefox and chrome
